version: '3'

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "8888:80"